comment:
  layout: "header, diff, components, files" # show component info in the PR comment

coverage:
  status:
    project:
      default:
        target: 45%
        threshold: 5%
    patch:
      default:
        informational: true
      
component_management:
  individual_components:
    - component_id: schema
      name: schema # Golang packages for schema
      paths:
        - "accessors/**"
        - "cmd/**"
        - "common/**"
        - "internal/**"
        - "profiles/**"
        - "sources/**"
        - "spanner/**"
        - "webv2/**"
      statuses:
        - type: project
          informational: true
    - component_id: orchestration
      name: orchestration
      paths:
        - "accessors/**"
        - "cmd/**"
        - "common/**"
        - "conversion/**"
        - "dao/**"
        - "internal/**"
        - "profiles/**"
        - "streaming/**"
        - "webv2/**"
      statuses:
        - type: project
          informational: true
    - component_id: legacy 
      name: legacy
      paths:
        - "accessors/**"
        - "cmd/**"
        - "common/**"
        - "profiles/**"
        - "sources/**"
        - "spanner/**"
        - "webv2/**"
      statuses:
        - type: project
          informational: true
    - component_id: frontend
      name: frontend # only frontend components
      paths:
        - "ui/**"
      statuses:
        - type: project
          informational: true
ignore:
  - ".docker"
  - ".github"
  - "docs"
  - "**/mocks.go"
