comment:
  layout: "header, diff, flags, files" # show flag info in the PR comment
flag_management:
  default_rules: # default rules that will be inherited by all flags
    statuses:
      - type: project # in this case every flag that doens't have a status defined will have a project type
        target: auto
        threshold: 5%
        informational: true
        branches:
          - master
  individual_flags:
    - name: frontend
      paths:
        - "ui/**"
      statuses: # each flag has its own status and corresponding configuration
        - type: project
          target: auto
          informational: true

ignore:
  - ".docker"
  - ".github"
  - "docs"