# syntax=docker/dockerfile:1

######################### BUILD STAGE 1 ############################
# This stage builds the HarbourBridge binary using its source code.

# Add the official Docker golang image as the base image for the build stage
FROM golang:latest AS build

# Set the default work directory as “/hbBin” in the container.
WORKDIR /hbBin

# Copy HarbourBrdige’s source code into the working directory.
COPY . ./
# Download HarbourBridge’s dependencies mentioned in the go.mod file.
RUN go mod tidy 
# Compile the source code and store the binary in the work directory /hbBin.
RUN make build-static  

######################### Release Stage ###########################
# This stage consists of the GCloud SDK and the HabrbourBridge binary.

# Add the Ubuntu base image from the Google Container Registry.
FROM marketplace.gcr.io/google/ubuntu1804:latest
# Set the default working directory.
# This directory binds with the host directory that is to store the output files generated by HarbourBridge.
WORKDIR /harbourBridge/harbour_bridge_output
# Create directory to store the HarbourBridge binary. 
RUN mkdir /harbourBridge/bin
# Create directory to store the dump files. This directory binds with the host directory that contains the dump files of the source database.
RUN mkdir /harbourBridge/sourceDump
# Copy the HarbourBridge binary from the build stage's hbBin directory to the release stage's habourBridge/bin directory
COPY --from=build /hbBin/harbourbridge /harbourBridge/bin

# Add Python3 to support GCloud SDK.
RUN apt update
RUN apt install -y python3

# Download the gcloud package
RUN curl https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-cli-391.0.0-linux-x86_64.tar.gz > /tmp/google-cloud-sdk.tar.gz

# Install the GCloud package
RUN mkdir -p /usr/local/gcloud \
  && tar -C /usr/local/gcloud -xf /tmp/google-cloud-sdk.tar.gz \
  && /usr/local/gcloud/google-cloud-sdk/install.sh

# Add gcloud to $PATH
ENV PATH $PATH:/usr/local/gcloud/google-cloud-sdk/bin

# Default command to execute when the container is run.
# NOTE : This command will be overridden by the HarborBridge migration commands.
CMD [ "/harbourBridge/bin/harbourbridge" ]