const initialData = {
  srcTables: [
    'AllTypes',
    'go.get',
    'production.brands',
    'production.categories',
    'production.products',
    'production.stocks',
    'sales.customers',
    'sales.order_items',
    'sales.orders',
    'sales.sales.where',
    'sales.staffs',
    'sales.stores',
  ],
  spTables: [
    'AllTypes',
    'go_get',
    'production_brands',
    'production_categories',
    'production_products',
    'production_stocks',
    'sales_customers',
    'sales_order_items',
    'sales_orders',
    'sales_sales_where',
    'sales_staffs',
    'sales_stores',
  ],

  colorCode: {
    AllTypes: 'OK',
    go_get: 'GOOD',
    production_brands: 'EXCELLENT',
    production_categories: 'EXCELLENT',
    production_products: 'EXCELLENT',
    production_stocks: 'EXCELLENT',
    sales_customers: 'EXCELLENT',
    sales_order_items: 'OK',
    sales_orders: 'EXCELLENT',
    sales_sales_where: 'GOOD',
    sales_staffs: 'EXCELLENT',
    sales_stores: 'EXCELLENT',
  },
  mapping: {
    AllTypes: [
      {
        spColName: 'Id',
        spDataType: 'INT64',
        srcColName: 'Id',
        srcDataType: 'int',
      },
      {
        spColName: 'BigInt',
        spDataType: 'INT64',
        srcColName: 'BigInt',
        srcDataType: 'bigint',
      },
      {
        spColName: 'Binary',
        spDataType: 'BYTES',
        srcColName: 'Binary',
        srcDataType: 'binary',
      },
      {
        spColName: 'Bit',
        spDataType: 'BOOL',
        srcColName: 'Bit',
        srcDataType: 'bit',
      },
      {
        spColName: 'Char',
        spDataType: 'STRING',
        srcColName: 'Char',
        srcDataType: 'char',
      },
      {
        spColName: 'Date',
        spDataType: 'DATE',
        srcColName: 'Date',
        srcDataType: 'date',
      },
      {
        spColName: 'DateTime',
        spDataType: 'TIMESTAMP',
        srcColName: 'DateTime',
        srcDataType: 'datetime',
      },
      {
        spColName: 'DateTime2',
        spDataType: 'TIMESTAMP',
        srcColName: 'DateTime2',
        srcDataType: 'datetime2',
      },
      {
        spColName: 'DateTimeOffset',
        spDataType: 'TIMESTAMP',
        srcColName: 'DateTimeOffset',
        srcDataType: 'datetimeoffset',
      },
      {
        spColName: 'Decimal',
        spDataType: 'NUMERIC',
        srcColName: 'Decimal',
        srcDataType: 'decimal',
      },
      {
        spColName: 'Float',
        spDataType: 'FLOAT64',
        srcColName: 'Float',
        srcDataType: 'float',
      },
      {
        spColName: 'Geography',
        spDataType: 'STRING',
        srcColName: 'Geography',
        srcDataType: 'geography',
      },
      {
        spColName: 'Geometry',
        spDataType: 'STRING',
        srcColName: 'Geometry',
        srcDataType: 'geometry',
      },
      {
        spColName: 'HierarchyId',
        spDataType: 'STRING',
        srcColName: 'HierarchyId',
        srcDataType: 'hierarchyid',
      },
      {
        spColName: 'Image',
        spDataType: 'BYTES',
        srcColName: 'Image',
        srcDataType: 'image',
      },
      {
        spColName: 'Int',
        spDataType: 'INT64',
        srcColName: 'Int',
        srcDataType: 'int',
      },
      {
        spColName: 'Money',
        spDataType: 'NUMERIC',
        srcColName: 'Money',
        srcDataType: 'money',
      },
      {
        spColName: 'NChar',
        spDataType: 'STRING',
        srcColName: 'NChar',
        srcDataType: 'nchar',
      },
      {
        spColName: 'NText',
        spDataType: 'STRING',
        srcColName: 'NText',
        srcDataType: 'ntext',
      },
      {
        spColName: 'Numeric',
        spDataType: 'NUMERIC',
        srcColName: 'Numeric',
        srcDataType: 'numeric',
      },
      {
        spColName: 'NVarChar',
        spDataType: 'STRING',
        srcColName: 'NVarChar',
        srcDataType: 'nvarchar',
      },
      {
        spColName: 'NVarCharMax',
        spDataType: 'STRING',
        srcColName: 'NVarCharMax',
        srcDataType: 'nvarchar',
      },
      {
        spColName: 'Real',
        spDataType: 'FLOAT64',
        srcColName: 'Real',
        srcDataType: 'real',
      },
      {
        spColName: 'SmallDateTime',
        spDataType: 'TIMESTAMP',
        srcColName: 'SmallDateTime',
        srcDataType: 'smalldatetime',
      },
      {
        spColName: 'SmallInt',
        spDataType: 'INT64',
        srcColName: 'SmallInt',
        srcDataType: 'smallint',
      },
      {
        spColName: 'SmallMoney',
        spDataType: 'NUMERIC',
        srcColName: 'SmallMoney',
        srcDataType: 'smallmoney',
      },
      {
        spColName: 'SQLVariant',
        spDataType: 'STRING',
        srcColName: 'SQLVariant',
        srcDataType: 'sql_variant',
      },
      {
        spColName: 'Text',
        spDataType: 'STRING',
        srcColName: 'Text',
        srcDataType: 'text',
      },
      {
        spColName: 'Time',
        spDataType: 'STRING',
        srcColName: 'Time',
        srcDataType: 'time',
      },
      {
        spColName: 'TimeStamp',
        spDataType: 'INT64',
        srcColName: 'TimeStamp',
        srcDataType: 'timestamp',
      },
      {
        spColName: 'TinyInt',
        spDataType: 'INT64',
        srcColName: 'TinyInt',
        srcDataType: 'tinyint',
      },
      {
        spColName: 'UniqueIdentifier',
        spDataType: 'STRING',
        srcColName: 'UniqueIdentifier',
        srcDataType: 'uniqueidentifier',
      },
      {
        spColName: 'VarBinary',
        spDataType: 'BYTES',
        srcColName: 'VarBinary',
        srcDataType: 'varbinary',
      },
      {
        spColName: 'VarBinaryMax',
        spDataType: 'BYTES',
        srcColName: 'VarBinaryMax',
        srcDataType: 'varbinary',
      },
      {
        spColName: 'VarChar',
        spDataType: 'STRING',
        srcColName: 'VarChar',
        srcDataType: 'varchar',
      },
      {
        spColName: 'VarCharMax',
        spDataType: 'STRING',
        srcColName: 'VarCharMax',
        srcDataType: 'varchar',
      },
      {
        spColName: 'Xml',
        spDataType: 'STRING',
        srcColName: 'Xml',
        srcDataType: 'xml',
      },
    ],
    go_get: [
      {
        spColName: 'A',
        spDataType: 'STRING',
        srcColName: 'A',
        srcDataType: 'nchar',
      },
    ],
    production_brands: [
      {
        spColName: 'brand_id',
        spDataType: 'INT64',
        srcColName: 'brand_id',
        srcDataType: 'int',
      },
      {
        spColName: 'brand_name',
        spDataType: 'STRING',
        srcColName: 'brand_name',
        srcDataType: 'varchar',
      },
    ],
    production_categories: [
      {
        spColName: 'category_id',
        spDataType: 'INT64',
        srcColName: 'category_id',
        srcDataType: 'int',
      },
      {
        spColName: 'category_name',
        spDataType: 'STRING',
        srcColName: 'category_name',
        srcDataType: 'varchar',
      },
    ],
    production_products: [
      {
        spColName: 'product_id',
        spDataType: 'INT64',
        srcColName: 'product_id',
        srcDataType: 'int',
      },
      {
        spColName: 'product_name',
        spDataType: 'STRING',
        srcColName: 'product_name',
        srcDataType: 'varchar',
      },
      {
        spColName: 'brand_id',
        spDataType: 'INT64',
        srcColName: 'brand_id',
        srcDataType: 'int',
      },
      {
        spColName: 'category_id',
        spDataType: 'INT64',
        srcColName: 'category_id',
        srcDataType: 'int',
      },
      {
        spColName: 'model_year',
        spDataType: 'INT64',
        srcColName: 'model_year',
        srcDataType: 'smallint',
      },
      {
        spColName: 'list_price',
        spDataType: 'NUMERIC',
        srcColName: 'list_price',
        srcDataType: 'decimal',
      },
    ],
    production_stocks: [
      {
        spColName: 'store_id',
        spDataType: 'INT64',
        srcColName: 'store_id',
        srcDataType: 'int',
      },
      {
        spColName: 'product_id',
        spDataType: 'INT64',
        srcColName: 'product_id',
        srcDataType: 'int',
      },
      {
        spColName: 'quantity',
        spDataType: 'INT64',
        srcColName: 'quantity',
        srcDataType: 'int',
      },
    ],
    sales_customers: [
      {
        spColName: 'customer_id',
        spDataType: 'INT64',
        srcColName: 'customer_id',
        srcDataType: 'int',
      },
      {
        spColName: 'first_name',
        spDataType: 'STRING',
        srcColName: 'first_name',
        srcDataType: 'varchar',
      },
      {
        spColName: 'last_name',
        spDataType: 'STRING',
        srcColName: 'last_name',
        srcDataType: 'varchar',
      },
      {
        spColName: 'phone',
        spDataType: 'STRING',
        srcColName: 'phone',
        srcDataType: 'varchar',
      },
      {
        spColName: 'email',
        spDataType: 'STRING',
        srcColName: 'email',
        srcDataType: 'varchar',
      },
      {
        spColName: 'street',
        spDataType: 'STRING',
        srcColName: 'street',
        srcDataType: 'varchar',
      },
      {
        spColName: 'city',
        spDataType: 'STRING',
        srcColName: 'city',
        srcDataType: 'varchar',
      },
      {
        spColName: 'state',
        spDataType: 'STRING',
        srcColName: 'state',
        srcDataType: 'varchar',
      },
      {
        spColName: 'zip_code',
        spDataType: 'STRING',
        srcColName: 'zip_code',
        srcDataType: 'varchar',
      },
    ],
    sales_order_items: [
      {
        spColName: 'order_id',
        spDataType: 'INT64',
        srcColName: 'order_id',
        srcDataType: 'int',
      },
      {
        spColName: 'item_id',
        spDataType: 'INT64',
        srcColName: 'item_id',
        srcDataType: 'int',
      },
      {
        spColName: 'product_id',
        spDataType: 'INT64',
        srcColName: 'product_id',
        srcDataType: 'int',
      },
      {
        spColName: 'quantity',
        spDataType: 'INT64',
        srcColName: 'quantity',
        srcDataType: 'int',
      },
      {
        spColName: 'list_price',
        spDataType: 'NUMERIC',
        srcColName: 'list_price',
        srcDataType: 'decimal',
      },
      {
        spColName: 'discount',
        spDataType: 'NUMERIC',
        srcColName: 'discount',
        srcDataType: 'decimal',
      },
    ],
    sales_orders: [
      {
        spColName: 'order_id',
        spDataType: 'INT64',
        srcColName: 'order_id',
        srcDataType: 'int',
      },
      {
        spColName: 'customer_id',
        spDataType: 'INT64',
        srcColName: 'customer_id',
        srcDataType: 'int',
      },
      {
        spColName: 'order_status',
        spDataType: 'INT64',
        srcColName: 'order_status',
        srcDataType: 'tinyint',
      },
      {
        spColName: 'order_date',
        spDataType: 'DATE',
        srcColName: 'order_date',
        srcDataType: 'date',
      },
      {
        spColName: 'required_date',
        spDataType: 'DATE',
        srcColName: 'required_date',
        srcDataType: 'date',
      },
      {
        spColName: 'shipped_date',
        spDataType: 'DATE',
        srcColName: 'shipped_date',
        srcDataType: 'date',
      },
      {
        spColName: 'store_id',
        spDataType: 'INT64',
        srcColName: 'store_id',
        srcDataType: 'int',
      },
      {
        spColName: 'staff_id',
        spDataType: 'INT64',
        srcColName: 'staff_id',
        srcDataType: 'int',
      },
    ],
    sales_sales_where: [
      {
        spColName: 'ID',
        spDataType: 'STRING',
        srcColName: 'ID',
        srcDataType: 'nchar',
      },
    ],
    sales_staffs: [
      {
        spColName: 'staff_id',
        spDataType: 'INT64',
        srcColName: 'staff_id',
        srcDataType: 'int',
      },
      {
        spColName: 'first_name',
        spDataType: 'STRING',
        srcColName: 'first_name',
        srcDataType: 'varchar',
      },
      {
        spColName: 'last_name',
        spDataType: 'STRING',
        srcColName: 'last_name',
        srcDataType: 'varchar',
      },
      {
        spColName: 'email',
        spDataType: 'STRING',
        srcColName: 'email',
        srcDataType: 'varchar',
      },
      {
        spColName: 'phone',
        spDataType: 'STRING',
        srcColName: 'phone',
        srcDataType: 'varchar',
      },
      {
        spColName: 'active',
        spDataType: 'INT64',
        srcColName: 'active',
        srcDataType: 'tinyint',
      },
      {
        spColName: 'store_id',
        spDataType: 'INT64',
        srcColName: 'store_id',
        srcDataType: 'int',
      },
      {
        spColName: 'manager_id',
        spDataType: 'INT64',
        srcColName: 'manager_id',
        srcDataType: 'int',
      },
    ],
    sales_stores: [
      {
        spColName: 'store_id',
        spDataType: 'INT64',
        srcColName: 'store_id',
        srcDataType: 'int',
      },
      {
        spColName: 'store_name',
        spDataType: 'STRING',
        srcColName: 'store_name',
        srcDataType: 'varchar',
      },
      {
        spColName: 'phone',
        spDataType: 'STRING',
        srcColName: 'phone',
        srcDataType: 'varchar',
      },
      {
        spColName: 'email',
        spDataType: 'STRING',
        srcColName: 'email',
        srcDataType: 'varchar',
      },
      {
        spColName: 'street',
        spDataType: 'STRING',
        srcColName: 'street',
        srcDataType: 'varchar',
      },
      {
        spColName: 'city',
        spDataType: 'STRING',
        srcColName: 'city',
        srcDataType: 'varchar',
      },
      {
        spColName: 'state',
        spDataType: 'STRING',
        srcColName: 'state',
        srcDataType: 'varchar',
      },
      {
        spColName: 'zip_code',
        spDataType: 'STRING',
        srcColName: 'zip_code',
        srcDataType: 'varchar',
      },
    ],
  },
}

export default initialData
