// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: migration_data.proto

package migration

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MigrationData_Source int32

const (
	MigrationData_SOURCE_UNSPECIFIED MigrationData_Source = 0
	MigrationData_MYSQL              MigrationData_Source = 1
	MigrationData_POSTGRESQL         MigrationData_Source = 2
	MigrationData_SQL_SERVER         MigrationData_Source = 4
	MigrationData_ORACLE             MigrationData_Source = 5
	MigrationData_CSV                MigrationData_Source = 6
)

// Enum value maps for MigrationData_Source.
var (
	MigrationData_Source_name = map[int32]string{
		0: "SOURCE_UNSPECIFIED",
		1: "MYSQL",
		2: "POSTGRESQL",
		4: "SQL_SERVER",
		5: "ORACLE",
		6: "CSV",
	}
	MigrationData_Source_value = map[string]int32{
		"SOURCE_UNSPECIFIED": 0,
		"MYSQL":              1,
		"POSTGRESQL":         2,
		"SQL_SERVER":         4,
		"ORACLE":             5,
		"CSV":                6,
	}
)

func (x MigrationData_Source) Enum() *MigrationData_Source {
	p := new(MigrationData_Source)
	*p = x
	return p
}

func (x MigrationData_Source) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MigrationData_Source) Descriptor() protoreflect.EnumDescriptor {
	return file_migration_data_proto_enumTypes[0].Descriptor()
}

func (MigrationData_Source) Type() protoreflect.EnumType {
	return &file_migration_data_proto_enumTypes[0]
}

func (x MigrationData_Source) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MigrationData_Source.Descriptor instead.
func (MigrationData_Source) EnumDescriptor() ([]byte, []int) {
	return file_migration_data_proto_rawDescGZIP(), []int{0, 0}
}

type MigrationData_SourceConnectionMechanism int32

const (
	MigrationData_SOURCE_CONNECTION_MECHANISM_UNSPECIFIED MigrationData_SourceConnectionMechanism = 0
	MigrationData_DIRECT_CONNECTION                       MigrationData_SourceConnectionMechanism = 1
	MigrationData_DB_DUMP                                 MigrationData_SourceConnectionMechanism = 2
	MigrationData_FILE                                    MigrationData_SourceConnectionMechanism = 3
)

// Enum value maps for MigrationData_SourceConnectionMechanism.
var (
	MigrationData_SourceConnectionMechanism_name = map[int32]string{
		0: "SOURCE_CONNECTION_MECHANISM_UNSPECIFIED",
		1: "DIRECT_CONNECTION",
		2: "DB_DUMP",
		3: "FILE",
	}
	MigrationData_SourceConnectionMechanism_value = map[string]int32{
		"SOURCE_CONNECTION_MECHANISM_UNSPECIFIED": 0,
		"DIRECT_CONNECTION":                       1,
		"DB_DUMP":                                 2,
		"FILE":                                    3,
	}
)

func (x MigrationData_SourceConnectionMechanism) Enum() *MigrationData_SourceConnectionMechanism {
	p := new(MigrationData_SourceConnectionMechanism)
	*p = x
	return p
}

func (x MigrationData_SourceConnectionMechanism) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MigrationData_SourceConnectionMechanism) Descriptor() protoreflect.EnumDescriptor {
	return file_migration_data_proto_enumTypes[1].Descriptor()
}

func (MigrationData_SourceConnectionMechanism) Type() protoreflect.EnumType {
	return &file_migration_data_proto_enumTypes[1]
}

func (x MigrationData_SourceConnectionMechanism) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MigrationData_SourceConnectionMechanism.Descriptor instead.
func (MigrationData_SourceConnectionMechanism) EnumDescriptor() ([]byte, []int) {
	return file_migration_data_proto_rawDescGZIP(), []int{0, 1}
}

type MigrationData_MigrationType int32

const (
	MigrationData_MIGRATION_TYPE_UNSPECIFIED MigrationData_MigrationType = 0
	MigrationData_SCHEMA_ONLY                MigrationData_MigrationType = 1
	MigrationData_DATA_ONLY                  MigrationData_MigrationType = 2
	MigrationData_SCHEMA_AND_DATA            MigrationData_MigrationType = 3
)

// Enum value maps for MigrationData_MigrationType.
var (
	MigrationData_MigrationType_name = map[int32]string{
		0: "MIGRATION_TYPE_UNSPECIFIED",
		1: "SCHEMA_ONLY",
		2: "DATA_ONLY",
		3: "SCHEMA_AND_DATA",
	}
	MigrationData_MigrationType_value = map[string]int32{
		"MIGRATION_TYPE_UNSPECIFIED": 0,
		"SCHEMA_ONLY":                1,
		"DATA_ONLY":                  2,
		"SCHEMA_AND_DATA":            3,
	}
)

func (x MigrationData_MigrationType) Enum() *MigrationData_MigrationType {
	p := new(MigrationData_MigrationType)
	*p = x
	return p
}

func (x MigrationData_MigrationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MigrationData_MigrationType) Descriptor() protoreflect.EnumDescriptor {
	return file_migration_data_proto_enumTypes[2].Descriptor()
}

func (MigrationData_MigrationType) Type() protoreflect.EnumType {
	return &file_migration_data_proto_enumTypes[2]
}

func (x MigrationData_MigrationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MigrationData_MigrationType.Descriptor instead.
func (MigrationData_MigrationType) EnumDescriptor() ([]byte, []int) {
	return file_migration_data_proto_rawDescGZIP(), []int{0, 2}
}

type MigrationData_TargetDialect int32

const (
	MigrationData_TARGET_DIALECT_UNSPECIFIED MigrationData_TargetDialect = 0
	MigrationData_GOOGLE_STANDARD_SQL        MigrationData_TargetDialect = 1
	MigrationData_POSTGRESQL_STANDARD_SQL    MigrationData_TargetDialect = 2
)

// Enum value maps for MigrationData_TargetDialect.
var (
	MigrationData_TargetDialect_name = map[int32]string{
		0: "TARGET_DIALECT_UNSPECIFIED",
		1: "GOOGLE_STANDARD_SQL",
		2: "POSTGRESQL_STANDARD_SQL",
	}
	MigrationData_TargetDialect_value = map[string]int32{
		"TARGET_DIALECT_UNSPECIFIED": 0,
		"GOOGLE_STANDARD_SQL":        1,
		"POSTGRESQL_STANDARD_SQL":    2,
	}
)

func (x MigrationData_TargetDialect) Enum() *MigrationData_TargetDialect {
	p := new(MigrationData_TargetDialect)
	*p = x
	return p
}

func (x MigrationData_TargetDialect) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MigrationData_TargetDialect) Descriptor() protoreflect.EnumDescriptor {
	return file_migration_data_proto_enumTypes[3].Descriptor()
}

func (MigrationData_TargetDialect) Type() protoreflect.EnumType {
	return &file_migration_data_proto_enumTypes[3]
}

func (x MigrationData_TargetDialect) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MigrationData_TargetDialect.Descriptor instead.
func (MigrationData_TargetDialect) EnumDescriptor() ([]byte, []int) {
	return file_migration_data_proto_rawDescGZIP(), []int{0, 3}
}

type MigrationData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A system generated id with prefix ‘SMT’ to identify that the request was
	// made via Spanner migration tool.
	MigrationRequestId *string `protobuf:"bytes,1,opt,name=migration_request_id,json=migrationRequestId,proto3,oneof" json:"migration_request_id,omitempty"`
	// Source for the migration.
	Source *MigrationData_Source `protobuf:"varint,2,opt,name=source,proto3,enum=MigrationData_Source,oneof" json:"source,omitempty"`
	// Mechanism used to fetch source data.
	SourceConnectionMechanism *MigrationData_SourceConnectionMechanism `protobuf:"varint,3,opt,name=source_connection_mechanism,json=sourceConnectionMechanism,proto3,enum=MigrationData_SourceConnectionMechanism,oneof" json:"source_connection_mechanism,omitempty"`
	// Type of migration.
	MigrationType *MigrationData_MigrationType `protobuf:"varint,4,opt,name=migration_type,json=migrationType,proto3,enum=MigrationData_MigrationType,oneof" json:"migration_type,omitempty"`
	// Type of target dialect.
	TargetDialect  *MigrationData_TargetDialect  `protobuf:"varint,5,opt,name=target_dialect,json=targetDialect,proto3,enum=MigrationData_TargetDialect,oneof" json:"target_dialect,omitempty"`
	SchemaPatterns *MigrationData_SchemaPatterns `protobuf:"bytes,6,opt,name=schema_patterns,json=schemaPatterns,proto3,oneof" json:"schema_patterns,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MigrationData) Reset() {
	*x = MigrationData{}
	mi := &file_migration_data_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MigrationData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MigrationData) ProtoMessage() {}

func (x *MigrationData) ProtoReflect() protoreflect.Message {
	mi := &file_migration_data_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MigrationData.ProtoReflect.Descriptor instead.
func (*MigrationData) Descriptor() ([]byte, []int) {
	return file_migration_data_proto_rawDescGZIP(), []int{0}
}

func (x *MigrationData) GetMigrationRequestId() string {
	if x != nil && x.MigrationRequestId != nil {
		return *x.MigrationRequestId
	}
	return ""
}

func (x *MigrationData) GetSource() MigrationData_Source {
	if x != nil && x.Source != nil {
		return *x.Source
	}
	return MigrationData_SOURCE_UNSPECIFIED
}

func (x *MigrationData) GetSourceConnectionMechanism() MigrationData_SourceConnectionMechanism {
	if x != nil && x.SourceConnectionMechanism != nil {
		return *x.SourceConnectionMechanism
	}
	return MigrationData_SOURCE_CONNECTION_MECHANISM_UNSPECIFIED
}

func (x *MigrationData) GetMigrationType() MigrationData_MigrationType {
	if x != nil && x.MigrationType != nil {
		return *x.MigrationType
	}
	return MigrationData_MIGRATION_TYPE_UNSPECIFIED
}

func (x *MigrationData) GetTargetDialect() MigrationData_TargetDialect {
	if x != nil && x.TargetDialect != nil {
		return *x.TargetDialect
	}
	return MigrationData_TARGET_DIALECT_UNSPECIFIED
}

func (x *MigrationData) GetSchemaPatterns() *MigrationData_SchemaPatterns {
	if x != nil {
		return x.SchemaPatterns
	}
	return nil
}

type MigrationData_SchemaPatterns struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Number of tables in the database being migrated.
	NumTables          *int32 `protobuf:"varint,1,opt,name=num_tables,json=numTables,proto3,oneof" json:"num_tables,omitempty"`
	MaxInterleaveDepth *int32 `protobuf:"varint,2,opt,name=max_interleave_depth,json=maxInterleaveDepth,proto3,oneof" json:"max_interleave_depth,omitempty"`
	// Number of interleaves in the database being migrated.
	NumInterleaves *int32 `protobuf:"varint,3,opt,name=num_interleaves,json=numInterleaves,proto3,oneof" json:"num_interleaves,omitempty"`
	// Number of indexes in the database being migrated.
	NumIndexes *int32 `protobuf:"varint,4,opt,name=num_indexes,json=numIndexes,proto3,oneof" json:"num_indexes,omitempty"`
	// number of tables with missing primary key in the database being migrated
	NumMissingPrimaryKey *int32 `protobuf:"varint,5,opt,name=num_missing_primary_key,json=numMissingPrimaryKey,proto3,oneof" json:"num_missing_primary_key,omitempty"`
	// Number of foreign key in the database being migrated.
	NumForeignKey *int32 `protobuf:"varint,6,opt,name=num_foreign_key,json=numForeignKey,proto3,oneof" json:"num_foreign_key,omitempty"`
	// Number of columns in the database.
	NumColumns *int32 `protobuf:"varint,7,opt,name=num_columns,json=numColumns,proto3,oneof" json:"num_columns,omitempty"`
	// Number of warnings occurred for the columns that didn’t map cleanly.
	NumWarnings   *int32 `protobuf:"varint,8,opt,name=num_warnings,json=numWarnings,proto3,oneof" json:"num_warnings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MigrationData_SchemaPatterns) Reset() {
	*x = MigrationData_SchemaPatterns{}
	mi := &file_migration_data_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MigrationData_SchemaPatterns) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MigrationData_SchemaPatterns) ProtoMessage() {}

func (x *MigrationData_SchemaPatterns) ProtoReflect() protoreflect.Message {
	mi := &file_migration_data_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MigrationData_SchemaPatterns.ProtoReflect.Descriptor instead.
func (*MigrationData_SchemaPatterns) Descriptor() ([]byte, []int) {
	return file_migration_data_proto_rawDescGZIP(), []int{0, 0}
}

func (x *MigrationData_SchemaPatterns) GetNumTables() int32 {
	if x != nil && x.NumTables != nil {
		return *x.NumTables
	}
	return 0
}

func (x *MigrationData_SchemaPatterns) GetMaxInterleaveDepth() int32 {
	if x != nil && x.MaxInterleaveDepth != nil {
		return *x.MaxInterleaveDepth
	}
	return 0
}

func (x *MigrationData_SchemaPatterns) GetNumInterleaves() int32 {
	if x != nil && x.NumInterleaves != nil {
		return *x.NumInterleaves
	}
	return 0
}

func (x *MigrationData_SchemaPatterns) GetNumIndexes() int32 {
	if x != nil && x.NumIndexes != nil {
		return *x.NumIndexes
	}
	return 0
}

func (x *MigrationData_SchemaPatterns) GetNumMissingPrimaryKey() int32 {
	if x != nil && x.NumMissingPrimaryKey != nil {
		return *x.NumMissingPrimaryKey
	}
	return 0
}

func (x *MigrationData_SchemaPatterns) GetNumForeignKey() int32 {
	if x != nil && x.NumForeignKey != nil {
		return *x.NumForeignKey
	}
	return 0
}

func (x *MigrationData_SchemaPatterns) GetNumColumns() int32 {
	if x != nil && x.NumColumns != nil {
		return *x.NumColumns
	}
	return 0
}

func (x *MigrationData_SchemaPatterns) GetNumWarnings() int32 {
	if x != nil && x.NumWarnings != nil {
		return *x.NumWarnings
	}
	return 0
}

var File_migration_data_proto protoreflect.FileDescriptor

const file_migration_data_proto_rawDesc = "" +
	"\n" +
	"\x14migration_data.proto\"\x85\f\n" +
	"\rMigrationData\x125\n" +
	"\x14migration_request_id\x18\x01 \x01(\tH\x00R\x12migrationRequestId\x88\x01\x01\x122\n" +
	"\x06source\x18\x02 \x01(\x0e2\x15.MigrationData.SourceH\x01R\x06source\x88\x01\x01\x12m\n" +
	"\x1bsource_connection_mechanism\x18\x03 \x01(\x0e2(.MigrationData.SourceConnectionMechanismH\x02R\x19sourceConnectionMechanism\x88\x01\x01\x12H\n" +
	"\x0emigration_type\x18\x04 \x01(\x0e2\x1c.MigrationData.MigrationTypeH\x03R\rmigrationType\x88\x01\x01\x12H\n" +
	"\x0etarget_dialect\x18\x05 \x01(\x0e2\x1c.MigrationData.TargetDialectH\x04R\rtargetDialect\x88\x01\x01\x12K\n" +
	"\x0fschema_patterns\x18\x06 \x01(\v2\x1d.MigrationData.SchemaPatternsH\x05R\x0eschemaPatterns\x88\x01\x01\x1a\x93\x04\n" +
	"\x0eSchemaPatterns\x12\"\n" +
	"\n" +
	"num_tables\x18\x01 \x01(\x05H\x00R\tnumTables\x88\x01\x01\x125\n" +
	"\x14max_interleave_depth\x18\x02 \x01(\x05H\x01R\x12maxInterleaveDepth\x88\x01\x01\x12,\n" +
	"\x0fnum_interleaves\x18\x03 \x01(\x05H\x02R\x0enumInterleaves\x88\x01\x01\x12$\n" +
	"\vnum_indexes\x18\x04 \x01(\x05H\x03R\n" +
	"numIndexes\x88\x01\x01\x12:\n" +
	"\x17num_missing_primary_key\x18\x05 \x01(\x05H\x04R\x14numMissingPrimaryKey\x88\x01\x01\x12+\n" +
	"\x0fnum_foreign_key\x18\x06 \x01(\x05H\x05R\rnumForeignKey\x88\x01\x01\x12$\n" +
	"\vnum_columns\x18\a \x01(\x05H\x06R\n" +
	"numColumns\x88\x01\x01\x12&\n" +
	"\fnum_warnings\x18\b \x01(\x05H\aR\vnumWarnings\x88\x01\x01B\r\n" +
	"\v_num_tablesB\x17\n" +
	"\x15_max_interleave_depthB\x12\n" +
	"\x10_num_interleavesB\x0e\n" +
	"\f_num_indexesB\x1a\n" +
	"\x18_num_missing_primary_keyB\x12\n" +
	"\x10_num_foreign_keyB\x0e\n" +
	"\f_num_columnsB\x0f\n" +
	"\r_num_warnings\"`\n" +
	"\x06Source\x12\x16\n" +
	"\x12SOURCE_UNSPECIFIED\x10\x00\x12\t\n" +
	"\x05MYSQL\x10\x01\x12\x0e\n" +
	"\n" +
	"POSTGRESQL\x10\x02\x12\x0e\n" +
	"\n" +
	"SQL_SERVER\x10\x04\x12\n" +
	"\n" +
	"\x06ORACLE\x10\x05\x12\a\n" +
	"\x03CSV\x10\x06\"v\n" +
	"\x19SourceConnectionMechanism\x12+\n" +
	"'SOURCE_CONNECTION_MECHANISM_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11DIRECT_CONNECTION\x10\x01\x12\v\n" +
	"\aDB_DUMP\x10\x02\x12\b\n" +
	"\x04FILE\x10\x03\"d\n" +
	"\rMigrationType\x12\x1e\n" +
	"\x1aMIGRATION_TYPE_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vSCHEMA_ONLY\x10\x01\x12\r\n" +
	"\tDATA_ONLY\x10\x02\x12\x13\n" +
	"\x0fSCHEMA_AND_DATA\x10\x03\"e\n" +
	"\rTargetDialect\x12\x1e\n" +
	"\x1aTARGET_DIALECT_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13GOOGLE_STANDARD_SQL\x10\x01\x12\x1b\n" +
	"\x17POSTGRESQL_STANDARD_SQL\x10\x02B\x17\n" +
	"\x15_migration_request_idB\t\n" +
	"\a_sourceB\x1e\n" +
	"\x1c_source_connection_mechanismB\x11\n" +
	"\x0f_migration_typeB\x11\n" +
	"\x0f_target_dialectB\x12\n" +
	"\x10_schema_patternsB\fZ\n" +
	"/migrationb\x06proto3"

var (
	file_migration_data_proto_rawDescOnce sync.Once
	file_migration_data_proto_rawDescData []byte
)

func file_migration_data_proto_rawDescGZIP() []byte {
	file_migration_data_proto_rawDescOnce.Do(func() {
		file_migration_data_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_migration_data_proto_rawDesc), len(file_migration_data_proto_rawDesc)))
	})
	return file_migration_data_proto_rawDescData
}

var file_migration_data_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_migration_data_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_migration_data_proto_goTypes = []any{
	(MigrationData_Source)(0),                    // 0: MigrationData.Source
	(MigrationData_SourceConnectionMechanism)(0), // 1: MigrationData.SourceConnectionMechanism
	(MigrationData_MigrationType)(0),             // 2: MigrationData.MigrationType
	(MigrationData_TargetDialect)(0),             // 3: MigrationData.TargetDialect
	(*MigrationData)(nil),                        // 4: MigrationData
	(*MigrationData_SchemaPatterns)(nil),         // 5: MigrationData.SchemaPatterns
}
var file_migration_data_proto_depIdxs = []int32{
	0, // 0: MigrationData.source:type_name -> MigrationData.Source
	1, // 1: MigrationData.source_connection_mechanism:type_name -> MigrationData.SourceConnectionMechanism
	2, // 2: MigrationData.migration_type:type_name -> MigrationData.MigrationType
	3, // 3: MigrationData.target_dialect:type_name -> MigrationData.TargetDialect
	5, // 4: MigrationData.schema_patterns:type_name -> MigrationData.SchemaPatterns
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_migration_data_proto_init() }
func file_migration_data_proto_init() {
	if File_migration_data_proto != nil {
		return
	}
	file_migration_data_proto_msgTypes[0].OneofWrappers = []any{}
	file_migration_data_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_migration_data_proto_rawDesc), len(file_migration_data_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_migration_data_proto_goTypes,
		DependencyIndexes: file_migration_data_proto_depIdxs,
		EnumInfos:         file_migration_data_proto_enumTypes,
		MessageInfos:      file_migration_data_proto_msgTypes,
	}.Build()
	File_migration_data_proto = out.File
	file_migration_data_proto_goTypes = nil
	file_migration_data_proto_depIdxs = nil
}
