origin_contact_points: 10.128.0.14,10.128.0.15
target_contact_points: 127.0.0.1
origin_username: cassandra
origin_password: cassandra
target_username: cassandra
target_password: cassandra
proxy_listen_address: 0.0.0.0
proxy_topology_addresses: 127.0.0.1
proxy_topology_index: 0
proxy_request_timeout_ms: 30000
proxy_max_client_connections: 30000
proxy_max_stream_ids: 30000
log_level: WARN
